//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payga
{
    using System;
    using System.Collections.Generic;
    
    public partial class added_to
    {
        public int client_id { get; set; }
        public int cart_number { get; set; }
        public int locked_number { get; set; }
        public int product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> cart_price { get; set; }
    
        public virtual locked_shopping_cart locked_shopping_cart { get; set; }
        public virtual product product { get; set; }
    }
}
