//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payga
{
    using System;
    using System.Collections.Generic;
    
    public partial class deposits_into_wallet
    {
        public int tracking_code { get; set; }
        public int id { get; set; }
        public decimal amount { get; set; }
    
        public virtual bank_transaction bank_transaction { get; set; }
        public virtual client client { get; set; }
    }
}
