//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payga
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount_code
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public discount_code()
        {
            this.applied_to = new HashSet<applied_to>();
        }
    
        public string dis_code { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> dis_limit { get; set; }
        public Nullable<int> usage_count { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<applied_to> applied_to { get; set; }
        public virtual private_code private_code { get; set; }
        public virtual public_code public_code { get; set; }
    }
}
