//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payga
{
    using System;
    using System.Collections.Generic;
    
    public partial class motherboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public motherboard()
        {
            this.sm_slot_compatible_with = new HashSet<sm_slot_compatible_with>();
            this.gpus = new HashSet<gpu>();
            this.cpus = new HashSet<cpu>();
            this.ram_stick = new HashSet<ram_stick>();
        }
    
        public int id { get; set; }
        public string chipset { get; set; }
        public int number_of_memory_slots { get; set; }
        public string memory_speed_range { get; set; }
        public decimal wattage { get; set; }
        public Nullable<decimal> height { get; set; }
        public decimal width { get; set; }
        public decimal depth { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sm_slot_compatible_with> sm_slot_compatible_with { get; set; }
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gpu> gpus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cpu> cpus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ram_stick> ram_stick { get; set; }
    }
}
