//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payga
{
    using System;
    using System.Collections.Generic;
    
    public partial class sm_slot_compatible_with
    {
        public int motherboard_id_sm { get; set; }
        public int ssd_id_sm { get; set; }
    
        public virtual motherboard motherboard { get; set; }
    }
}
