//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payga
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int tracking_code { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
    
        public virtual bank_transaction bank_transaction { get; set; }
        public virtual wallet_transaction wallet_transaction { get; set; }
        public virtual locked_shopping_cart locked_shopping_cart { get; set; }
        public virtual client client { get; set; }
    }
}
