CREATE DATABASE IF NOT EXISTS payga;
USE payga;

CREATE TABLE RAM_STICK (
    ID INT NOT NULL,
    Capacity INT NOT NULL,
    Wattage DECIMAL(6, 2) DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_RAM_STICK_PRODUCT FOREIGN KEY (ID)
        REFERENCES product (id)
) ENGINE=InnoDB;
