CREATE TABLE SSD (
    ID INT NOT NULL,
    Capacity INT NOT NULL,
    Wattage DECIMAL(6, 2) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_SSD_PRODUCT FOREIGN KEY (ID) 
        REFERENCES product (id) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);
