//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class applied_to
    {
        public int client_id { get; set; }
        public int cart_number { get; set; }
        public int locked_number { get; set; }
        public string app_code { get; set; }
        public System.DateTime app_time { get; set; }
    
        public virtual discount_code discount_code { get; set; }
        public virtual locked_shopping_cart locked_shopping_cart { get; set; }
    }
}
