//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class bank_transaction
    {
        public int tracking_code { get; set; }
        public string card_number { get; set; }
    
        public virtual transaction transaction { get; set; }
        public virtual deposits_into_wallet deposits_into_wallet { get; set; }
    }
}
