//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cooler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cooler()
        {
            this.cpus = new HashSet<cpu>();
        }
    
        public int id { get; set; }
        public decimal maximum_rotational_speed { get; set; }
        public decimal wattage { get; set; }
        public decimal fan_size { get; set; }
        public string cooling_method { get; set; }
        public Nullable<decimal> height { get; set; }
        public decimal width { get; set; }
        public decimal depth { get; set; }
    
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cpu> cpus { get; set; }
    }
}
