//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cpu()
        {
            this.coolers = new HashSet<cooler>();
            this.motherboards = new HashSet<motherboard>();
        }
    
        public int id { get; set; }
        public int maximum_addressable_memory_limit { get; set; }
        public decimal boost_frequency { get; set; }
        public decimal base_frequency { get; set; }
        public int number_of_cores { get; set; }
        public int number_of_Threads { get; set; }
        public string microarchitecture { get; set; }
        public string generation { get; set; }
        public decimal wattage { get; set; }
    
        public virtual product product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cooler> coolers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<motherboard> motherboards { get; set; }
    }
}
