//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_1Entities : DbContext
    {
        public db_1Entities()
            : base("name=db_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<added_to> added_to { get; set; }
        public virtual DbSet<address> addresses { get; set; }
        public virtual DbSet<applied_to> applied_to { get; set; }
        public virtual DbSet<bank_transaction> bank_transaction { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<cooler> coolers { get; set; }
        public virtual DbSet<cpu> cpus { get; set; }
        public virtual DbSet<deposits_into_wallet> deposits_into_wallet { get; set; }
        public virtual DbSet<discount_code> discount_code { get; set; }
        public virtual DbSet<gpu> gpus { get; set; }
        public virtual DbSet<hdd> hdds { get; set; }
        public virtual DbSet<locked_shopping_cart> locked_shopping_cart { get; set; }
        public virtual DbSet<motherboard> motherboards { get; set; }
        public virtual DbSet<p_case> p_case { get; set; }
        public virtual DbSet<power_supply> power_supply { get; set; }
        public virtual DbSet<private_code> private_code { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<public_code> public_code { get; set; }
        public virtual DbSet<ram_stick> ram_stick { get; set; }
        public virtual DbSet<refer> refers { get; set; }
        public virtual DbSet<shopping_cart> shopping_cart { get; set; }
        public virtual DbSet<sm_slot_compatible_with> sm_slot_compatible_with { get; set; }
        public virtual DbSet<SSD> SSDs { get; set; }
        public virtual DbSet<transaction> transactions { get; set; }
        public virtual DbSet<vip_client> vip_client { get; set; }
        public virtual DbSet<wallet_transaction> wallet_transaction { get; set; }
        public virtual DbSet<Cart_Total_Discount> Cart_Total_Discount { get; set; }
    }
}
