//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_case
    {
        public int id { get; set; }
        public int number_of_fans { get; set; }
        public decimal fan_size { get; set; }
        public decimal wattage { get; set; }
        public string case_type { get; set; }
        public string material { get; set; }
        public string color { get; set; }
        public Nullable<decimal> height { get; set; }
        public decimal width { get; set; }
        public decimal depth { get; set; }
    
        public virtual product product { get; set; }
    }
}
