//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class private_code
    {
        public string pri_code { get; set; }
        public int id { get; set; }
        public System.DateTime pri_time { get; set; }
    
        public virtual client client { get; set; }
        public virtual discount_code discount_code { get; set; }
    }
}
