//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class refer
    {
        public int referee { get; set; }
        public Nullable<int> referrer { get; set; }
    
        public virtual client client { get; set; }
        public virtual client client1 { get; set; }
    }
}
