//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CartTotalAfterIssuedFor
    {
        public int cart_number { get; set; }
        public int locked_number { get; set; }
        public Nullable<decimal> final_total { get; set; }
    }
}
