//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TransactionDetails
    {
        public int tracking_code { get; set; }
        public Nullable<System.DateTime> transaction_time { get; set; }
        public int issued_for_id { get; set; }
        public int cart_number { get; set; }
        public int locked_number { get; set; }
    }
}
